version: '3'

services:
  # MySQL database for Magento
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: magentodb
      MYSQL_USER: magentouser
      MYSQL_PASSWORD: MyPassword
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - magento-db-data:/var/lib/mysql

  # Magento web server
  magento:
    image: fir3eye/magento:v2
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MAGENTO_DB_HOST: db
      MAGENTO_DB_USER: magentouser
      MAGENTO_DB_PASSWORD: MyPassword
      MAGENTO_DB_NAME: magentodb
      MAGENTO_ADMIN_USER: admin
      MAGENTO_ADMIN_PASSWORD: admin123
      MAGENTO_ADMIN_EMAIL: admin@example.com
      MAGENTO_BASE_URL: http://localhost:8080/
    volumes:
      - magento-data:/var/www/html

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      
volumes:
  magento-db-data:
  magento-data:
  
