services:
  # MySQL database for Magento
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: magentodb
      MYSQL_USER: magentouser
      MYSQL_PASSWORD: MyPassword
      MYSQL_ROOT_PASSWORD: admin

  # Magento web server
  magento:
    image: dockt35t/magento:v1
    container_name: magento_ap
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MAGENTO_DB_HOST: db
      MAGENTO_DB_USER: magentouser
      MAGENTO_DB_PASSWORD: MyPassword
      MAGENTO_DB_NAME: magentodb
      MAGENTO_ADMIN_USER: admin
      MAGENTO_ADMIN_PASSWORD: admin123
      MAGENTO_ADMIN_EMAIL: admin@example.com
      SERVER_IP: 35.154.23.28

    entrypoint: /var/www/html/run.sh
#    volumes:
 #     - magento-db:/var/www/html
  #    - var/www/html/app
  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
    ports:
      - "9200:9200"
#volumes:
#  magento-db:
