name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - master  # Trigger on pushes to main branch, change as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh-client

      - name: Sync Files to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          REMOTE_PORT: 22
          TARGET: /var/www/html  # Change to your target directory on EC2
          ARGS: "-rltgoDzvO"     # rsync options
          SOURCE: "./"           # Sync entire repo, change if needed
          REMOTE_HOST: ${{ secrets.EC2_HOST }}   # EC2 IP or hostname
          REMOTE_USER: ubuntu                     # EC2 username
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH key secret

      - name: Execute Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            docker-compose up -d 
