name: Deploy Magento Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}

      - name: Use Private Key
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          # Use the private key as needed in your workflow
          # Example: ssh-add private_key.pem
        env:
          PRIVATE_KEY: ${{ secrets.YOUR_PRIVATE_KEY_SECRET }}

      - name: Docker Compose Pull and Up
        run: |
          docker-compose pull
          docker-compose up -d
