name: CI/CD Pipeline

on:
  push:
    branches: [ master ]  # Change to 'main' if your default branch is named 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Images
      run: |
        docker-compose build
        docker-compose push
        
    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 700 private_key

    - name: Deploy to Server
      run: |
        ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
        docker-compose -f /home/ubuntu/magento3/docker-compose.yml pull
        docker-compose -f /home/ubuntu/magento3/docker-compose.yml up -d
        "
